“Clean”,
        “Read”,
        “Write”,
        “Draw”,
        “Talk”,
        “Drink”,
        “Sleep”,
        “Study”,
        “Skin”,
        “Brain”,
        “Bone”,
        “Heal”,
        “Pajamas”,
        “Porch”,
        “Follow”,
        “Focus”,
        “Idea”,
        “Travel around the world”,
        “Field”,
        “Wear”,

        “Grow up”,
        “Cure”,
        “diseases”,
        “Umbrella”,
        “Pilot”,
        “Space shuttle”,
        “Spacesuit”,
        “White coat”,
        “Hospital”,
        “Uniform”,
        “Become”,
        “Both”,
        “Sunglasses”,
        “Ocean”,
        “Hold”,
        “Seaweed”,
        “Strong”,
        “Float”,
        “Take care of sick people”,
        “Wrap”,
        “half”,

        “plan”,
        “stay home”,
        “go on a trip”,
        “decide”,
        “relax”,
        “expensive”,
        “everyone”,
        “library”,
        “active”,
        “stay inside”,
        “go outside”,
        “volleyball”,
        “far”,
        “cheap”,
        “maybe”,
        “mall”,
        “close”,
        “travel”,
        “arcade”,
        “habit”,

        “watch a movie”,
        “listen to music”,
        “talk on the phone”,
        “take a rest”,
        “take a picture”,
        “cricket”,
        “make a mask”,
        “bake cookies”,
        “dragonfly”,
        “lie down”,
        “run away”,
        “degree”,
        “wake up”,
        “temperature”,
        “Celsius”,
        “Tradition”,
        “Lucky”,
        “Thermometer”,
        “Enjoy”,
        “Pen pal”,

        “Introduce”,
        “Delicious”,
        “Activity”,
        “Festival”,
        “Country”,
        ‘Lovely”,
        “Join”,
        “Foreigner”,
        “Order”,
        “Garbage”,
        “Vacation”,
        “Sometimes”,
        “Advice”,
        “Interview”,
        “Project”,
        “Enough”,
        “Favorite”,
        “A little”,
        “Practice”,
        “friendly”,
